### ISSUE TITLE
Rework filters for new map tiles

### ISSUE THREAD

**Issue by danrademacher** [OpenHistoricalMap/mbgl-timeslider#4]
The new tech stack for OHM will be using tiles we can preview here:
http://a16ccd46b40d243f6b46ee60df7d70fc-1849580256.us-east-1.elb.amazonaws.com:9090/#14.000/48.57386/7.81519

The code in this repo runs and displays the map without errors
![image](https://user-images.githubusercontent.com/1423200/80939371-4e339880-8d91-11ea-8d8c-87792bad7e07.png)

But it also does not filter anything one the map.

In [our existing demo using Tessera to serve OpenMaptiles vtiles](https://open-historical-map-labs.github.io/openhistoricaltiles/#13.355/48.57240/7.81240/1803,1669-2019) we see this border appear and disappear:
![1rwUuBEQj6](https://user-images.githubusercontent.com/1423200/80939506-b7b3a700-8d91-11ea-9672-a7c74425af8b.gif)

In the new map, the border shows up regardless:
![image](https://user-images.githubusercontent.com/1423200/80939540-d7e36600-8d91-11ea-92b3-2447f7f4b2d4.png)

In the inspector, we can see the boundary:
![image](https://user-images.githubusercontent.com/1423200/80939846-c484ca80-8d92-11ea-958d-a13c7e15aeb8.png)

http://a16ccd46b40d243f6b46ee60df7d70fc-1849580256.us-east-1.elb.amazonaws.com:9090/#12/48.5662/7.7913

A bit of a pain to get the details when so much is stacked on top of each other, but here we can see that the feature seems to have all the required attributes:
```
osm_id:18446744073706869000
end_date:1803
end_decdate:1803.99863
admin_level:2
name:Markgrafschaft Baden
type:administrative
start_date:1790..1803
```

So need to figure out why it's not being filtered out when the timeslider year is `>1803.99863`

**Comment by danrademacher** [comment]
And the new tiles' schema is here:
https://github.com/developmentseed/osm-seed/blob/ohm/tiler-server/config/config.toml#L38

And indeed, `osm_id` and the needed date values are being passed into the tiles.

**Comment by danrademacher** [comment]
Using the console messaging from the tile inspector, I got these properties for that feature:

![image](https://user-images.githubusercontent.com/1423200/81014471-c5107600-8e11-11ea-800b-aa582bb082d1.png)

```
id: 18446744073706869000
layer:
   id: "admin_lines"
   layout: {visibility: "visible"}
   paint: {fill-color: "rgba(15,190,3,0.1)", fill-outline-color: "#0fbe03"}
   source: "osm"
   source-layer: "admin_lines"
   type: "fill"
properties:
   admin_level: 2
   end_date: "1803"
   end_decdate: 1803.99863
   name: "Markgrafschaft Baden"
   start_date: "1790..1803"
   type: "administrative"
```
